package com.tamam.simfikri.ui.component.view.frame;

import com.tamam.simfikri.ui.component.dialog.DialogAbout;
import com.tamam.simfikri.ui.component.dialog.DialogLogin;
import com.tamam.simfikri.ui.component.dialog.DialogServer;
import com.tamam.simfikri.ui.component.dialog.DialogTheme;
import com.tamam.simfikri.ui.component.frame.IFrameSetup;
import com.tamam.simfikri.ui.component.view.desktoppane.DesktopPaneMain;
import com.tamam.simfikri.ui.component.view.internalframe.dashboard.InternalFrameDashboard;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.annotation.PostConstruct;
import javax.swing.ImageIcon;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author <a href="fauzi.knightmaster.achmad@gmail.com">Achmad Fauzi</a>
 */
@Component
public class FrameMain extends javax.swing.JFrame {
    
    private static final long serialVersionUID = -7864902051693765103L;
    private Logger logger = LoggerFactory.getLogger(FrameMain.class);
    
    final Toolkit toolkit = Toolkit.getDefaultToolkit();
    final Dimension screenSize = toolkit.getScreenSize();
    
    @Autowired
    private IFrameSetup frameSetup;
    
    @Autowired
    private DialogTheme dialogTheme;
    
    @Autowired
    private DialogLogin dialogLogin;
    
    @Autowired
    private DialogAbout dialogAbout;
    
    @Autowired
    private DialogServer dialogServer;
    
    @Autowired
    private DesktopPaneMain desktopPaneMain;        
    
    @Autowired
    private InternalFrameDashboard internalFrameDashboard;        
    
    @PostConstruct
    public void setupFrame(){        
        frameSetup.doCompleteSetup(FrameMain.this);                
        initButton();
        setMenuVisibility(false);        
        setContentPane(desktopPaneMain);
    }
    
    private void initButton(){
        menuMain.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/menu-main.png")));
        subMenuDashboard.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/dashboard-small.png")));        
        menuLogin.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/menu-login.png")));
        subMenuLogin.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/sub-menu-login.png")));
        subMenuLogout.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/menu-logout.png")));
        menuSetting.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/menu-setting.png")));
        subMenuTheme.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/menu-theme.png")));
        subMenuAbout.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/menu-about.png")));
        subMenuServer.setIcon(new ImageIcon(getClass().getClassLoader().getResource("assets/bt-network.png")));
    }
    
    public void setMenuVisibility(boolean b){
        menuMain.setVisible(b);
        subMenuDashboard.setVisible(b);
        subMenuLogin.setVisible(!b);
        subMenuLogout.setVisible(b);
    }
    
    public FrameMain() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        subMenuDashboard = new javax.swing.JMenuItem();
        menuLogin = new javax.swing.JMenu();
        subMenuLogin = new javax.swing.JMenuItem();
        subMenuLogout = new javax.swing.JMenuItem();
        menuSetting = new javax.swing.JMenu();
        subMenuTheme = new javax.swing.JMenuItem();
        subMenuAbout = new javax.swing.JMenuItem();
        subMenuServer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boot Application");

        menuMain.setText("Main");

        subMenuDashboard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        subMenuDashboard.setText("Dashboard");
        subMenuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuDashboardActionPerformed(evt);
            }
        });
        menuMain.add(subMenuDashboard);

        menuBar.add(menuMain);

        menuLogin.setText("Auth");

        subMenuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        subMenuLogin.setText("Login");
        subMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLoginActionPerformed(evt);
            }
        });
        menuLogin.add(subMenuLogin);

        subMenuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        subMenuLogout.setText("Logout");
        subMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLogoutActionPerformed(evt);
            }
        });
        menuLogin.add(subMenuLogout);

        menuBar.add(menuLogin);

        menuSetting.setText("setting");

        subMenuTheme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        subMenuTheme.setText("Theme");
        subMenuTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuThemeActionPerformed(evt);
            }
        });
        menuSetting.add(subMenuTheme);

        subMenuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        subMenuAbout.setText("About");
        subMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuAboutActionPerformed(evt);
            }
        });
        menuSetting.add(subMenuAbout);

        subMenuServer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        subMenuServer.setText("Server");
        subMenuServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuServerActionPerformed(evt);
            }
        });
        menuSetting.add(subMenuServer);

        menuBar.add(menuSetting);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuDashboardActionPerformed
        if (internalFrameDashboard != null) {
            internalFrameDashboard.dispose();
        }        
        desktopPaneMain.add(internalFrameDashboard);
        int x = (screenSize.width - this.WIDTH) / 6;
        int y = (screenSize.height - this.HEIGHT) / 10;
        internalFrameDashboard.setSize(900, 550);
        internalFrameDashboard.setLocation(x, y);
        internalFrameDashboard.setVisible(true);    
    }//GEN-LAST:event_subMenuDashboardActionPerformed

    private void subMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLoginActionPerformed
        dialogLogin.setFrameMain(this);
        dialogLogin.init();
        dialogLogin.setVisible(true);
    }//GEN-LAST:event_subMenuLoginActionPerformed

    private void subMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLogoutActionPerformed
        setMenuVisibility(false);
    }//GEN-LAST:event_subMenuLogoutActionPerformed

    private void subMenuThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuThemeActionPerformed
        dialogTheme.setComponent(this);
        dialogTheme.init();
        dialogTheme.setVisible(true);
    }//GEN-LAST:event_subMenuThemeActionPerformed

    private void subMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuAboutActionPerformed
        dialogAbout.setVisible(true);
    }//GEN-LAST:event_subMenuAboutActionPerformed

    private void subMenuServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuServerActionPerformed
        dialogServer.setFrameMain(this);
        dialogServer.init();
        dialogServer.setVisible(true);
    }//GEN-LAST:event_subMenuServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenu menuMain;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JMenuItem subMenuAbout;
    private javax.swing.JMenuItem subMenuDashboard;
    private javax.swing.JMenuItem subMenuLogin;
    private javax.swing.JMenuItem subMenuLogout;
    private javax.swing.JMenuItem subMenuServer;
    private javax.swing.JMenuItem subMenuTheme;
    // End of variables declaration//GEN-END:variables
}
